server:
  port: 3450

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    username: root
    password: hn123456Aa
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

